### ISSUE TITLE
i try to play music than got error

### ISSUE THREAD

**Issue by ismamilahi** [SeasonPhan/MuseHeart-MusicBot-EN#4]
Error while playing the song: https://www.youtube.com/watch?v=IW0QkXpQs3k
Server: something.host
{'exception': {'cause': 'com.sedmelluq.discord.lavaplayer.tools.FriendlyException: '
                        'This video is not available',
               'message': 'This video is not available',
               'severity': 'common'},
 'guildId': '1003027554703265953',
 'op': 'event',
 'player': <volume=100 current_position=00:00 queue=0 loop=False EQ="Flat" guild="Ticket Pro And Nexus Support" node="something.host" keep_connected="False">,
 'track': {'encoded': 'QAAA6AMAR05vIENvcHlyaWdodCBNdXNpYyBQb3AgLSBUb3AgMjAgTmV3IFBvcCBTb25ncyAyMDIyIC0gUm95YWx0eSBGcmVlIE11c2ljAA9NdXNpYyBUbyBMaXN0ZW4AAAAAADiYSAALSVcwUWtYcFFzM2sAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1JVzBRa1hwUXMzawEANGh0dHBzOi8vaS55dGltZy5jb20vdmkvSVcwUWtYcFFzM2svbWF4cmVzZGVmYXVsdC5qcGcAAAd5b3V0dWJlAAAAAAAAAAA=',
           'info': {'artworkUrl': 'https://i.ytimg.com/vi/IW0QkXpQs3k/maxresdefault.jpg',
                    'author': 'Music To Listen',
                    'identifier': 'IW0QkXpQs3k',
                    'isSeekable': True,
                    'isStream': False,
                    'isrc': None,
                    'length': 3709000,
                    'position': 0,
                    'sourceName': 'youtube',
                    'title': 'No Copyright Music Pop - Top 20 New Pop Songs '
                             '2022 - Royalty Free Music',
                    'uri': 'https://www.youtube.com/watch?v=IW0QkXpQs3k'},
           'pluginInfo': {},
           'userData': {}},
 'type': 'TrackExceptionEvent'}

**Comment by SeasonPhan** [comment]
This version of the bot hasnt been updated for quite a long time now
i will merge new changes soon and hope it fixes the problems

**Comment by ismamilahi** [comment]
okay please do this

**Comment by SeasonPhan** [comment]
> ok please do this

i have updated the bot and so far no issue running with public lavalink servers
